apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revovely-website-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  
spec:
  rules:
  - host: revovely.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: revovely-website-service
            port:
              number: 80
 